# Generated by Django 4.1.1 on 2022-09-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
